GET http://localhost:8080/produtos/CAMISAS
Accept: application/json

###
POST http://localhost:8080/categoria
Content-Type: application/json

{
  "nome": "CAMISAS"
}

###
GET http://localhost:8080/produtos
Accept: application/json

###
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome":"CAMISA BRANCA",
  "descricao": "CAMISA TAMANHO M",
  "preco" : 160,
  "urlImagem": "https://dw0jruhdg6fis.cloudfront.net/producao/24866653/G/camisa-branca-malha-pp-100--poliester-.webp",
  "categoria": "CAMISAS"

}







